spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    password: wbl.123
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jpa:
    hibernate:
      ddl-auto: update       #更新或创建表
    show-sql: true         #控制台显示sql语句